### ISSUE TITLE
Changing layers results in unwanted key presses

### ISSUE THREAD

**Issue by kurtharriger** [technomancy/atreus-firmware#12]
I'm having a hard time figuring out how to change layers without unwanted side-effects.

I remapped backspace to level 3 in all levels including level 0.  The space key to level 0 in all modes except level 0.

I initially noticed the issue where pressing space to return to level 0 also inserted a space.  I figured it was still picking up the key as pressed when it started the next loop so I tried moving level switching to the end of the loop so that the keys get cleared at the beginning of the next loop... but still not really working for me.  

The fn key would mostly worked but in some apps it seemed that it inserted a new line or otherwise caused the cursor to move down but not sure why or what it was sending.  

My level 3 function was working, but now perhaps after creating a post function it seems to insert a backspace when pressed, which baffles me because it is not mapped to backspace in any level.

My latest attempt to get this working are on my fork here https://github.com/kurtharriger/atreus-firmware

**Comment by technomancy** [comment]
I think the increased delay in deactivating the `fn` layer I added a while ago should have taken care of this.
