### ISSUE TITLE
Double-duty keys

### ISSUE THREAD

**Issue by technomancy** [technomancy/atreus-firmware#2]
Should be able to bind a key to a modifier when held but an insertion when pressed/released on its own.

**Comment by dougcole** [comment]
@technomancy that'd be cool too!

**Comment by dougcole** [comment]
I just finished up a very non-general hack to support dual use keys here: https://github.com/dougcole/atreus-firmware/blob/dual_use_keys/atreus.c#L190-L222

I'm going to use it for a while and see how I like it and if it works well I'll clean it up and submit it here as a pull request.

**Comment by technomancy** [comment]
Sounds great; let us know how it goes!

**Comment by dougcole** [comment]
just as an update, my code above is stuck hitting weird timing issues trying to get the keyboard to never return the secondary value after using a key as a modifier. It works perfectly unless you hold down the modifier too long after finishing a key combo at which point it also returns the secondary value.

I switched to using the tmk firmware, so probably won't be investing more time in this. I'll leave my code up if someone else is interested and wants to try and fix my bugs :smile:.

**Comment by technomancy** [comment]
Yeah, I'm starting to think focusing on TMK is a better use of time. Right now it's pretty gnarly, but I'm working to make it a bit nicer to work with.

**Comment by dougcole** [comment]
yeah, the code is a little crazy, but the documentation is good and it does everything I want!

**Comment by technomancy** [comment]
Closing this as other firmwares are clear improvements over this one.
