### ISSUE TITLE
How long does it take to do the first firmware upload?

### ISSUE THREAD

**Issue by pzula** [technomancy/atreus-firmware#24]
Hi Phil!

Finally got around to putting my keyboard together today and I am using the A-star controller with the PCB. I downloaded the firmware and have gotten into bootloader mode hit 'make upload' when it was pulsing, but I've waited quite a while and the process never finishes. Am I doing something wrong, or is the Mac attempting to identify this keyboard getting in the way of the process?

**Comment by pzula** [comment]
I've tried several things and I'm starting to wonder if it makes a difference that I am using Mavericks? I haven't been able to get the first flash of the firmware to work. It just gets stuck on sleep mode and never finishes.

**Comment by technomancy** [comment]
Sorry you're having trouble with this. One possible cause of this problem could be getting the path to the USB device wrong. Normally on OS X you use `make upload USB=/dev/cu.usbmodem1411` but it's possible some versions of OS X place the USB device at a different path; I haven't tested it on newer releases.

You can identify the USB device like so:

```
$ ls /dev > /tmp/dev-off # run this while the device is out of bootloader mode
$ ls /dev > /tmp/dev-on # run this while the device is in bootloader mode
$ diff /tmp/dev-off /tmp/dev-on
```

This should get you the correct path.

**Comment by pzula** [comment]
Yup! The USB path was incorrect :+1: Mine was `/dev/tty.usbmodem1421`. Thank you!

**Comment by technomancy** [comment]
Glad you got it working. I tried to clarify this in a6aa4ec, do you think that's a good explanation?

**Comment by pzula** [comment]
@technomancy I didn't actually have any luck with using the diff -- it wasn't any different when it was in bootloader mode vs when it wasn't. So I just looked for the entry with `usb` in it and gave it a whirl in the Makefile :)
