### ISSUE TITLE
atreus.el in melpa?

### ISSUE THREAD

**Issue by ardumont** [technomancy/atreus-firmware#25]
Hello,

Can I add the `atreus.el` file in the melpa repository?

Cheers,

**Comment by ardumont** [comment]
Recipes ready: https://github.com/ardumont/melpa/blob/add-atreus/recipes/atreus

**Comment by technomancy** [comment]
I would rather not as I may deprecate this repo in favor of TMK. In any case this code is meant to be run from a makefile, not interactively.

Sent from my mobile. Please excuse top-posting and other infelicities.

**Comment by ardumont** [comment]
Ok.

That's what I sensed from multiple writings so I thought of asking.
