### ISSUE TITLE
Momentary L2

### ISSUE THREAD

**Issue by technomancy** [technomancy/atreus-firmware#26]
As discussed in http://librelist.com/browser//atreus/2015/1/4/f-key-row/ it would be good to be able to reach L2 in a non-modal way.

Right now the arrow keys and F-keys are a bit harder to hit than the regular `fn` layer keys because you have to hit a key to switch to L2 mode, hit the key, then switch out of L2. If we could make L2 active only while a certain combination is held, it would be more convenient. `fn+shift` could bring it to L2, since shift is redundant on the `fn` layer.

**Comment by jevonearth** [comment]
+1 for `fn+shift`

**Comment by technomancy** [comment]
I never was able to sort out the bug I was seeing on this. However, I've
been playing with another approach for making the arrows more
accessible. I sent it to the mailing list, but the mailing list was
down, so I posted a copy here:

  http://p.hagelb.org/atreus-alternate-layouts.html

Interested in getting feedback on this.

**Comment by dbordak** [comment]
How about something like this?

```
    pgup   up   pgdn   {     }       $     7   8   9   *
    left  down  right  [     ]       &     4   5   6   +
     !     @      #    (     )       `     1   2   3   \
```

You lose the arrows being over the resting position, but you get the brace symmetry back, and the pgup/pgdn nestling in the directional triangle is a familiar and comfortable position. Plus, the directions would be directly over wasd, which would make sense from that perspective -- your hand rests in the same location for either type of directional input

**Comment by technomancy** [comment]
Yeah, I toyed around with an arrangement like that a bit. The main
reason I didn't like it is that of all the keys on the fn layer, for me
the parens, brackets, and braces are the most common, and having to hit
all six of them with the same finger is a bit of a drag.

Personally I like being able to hit pageup and pagedown with the right
hand since that way you can do it one-handed. I don't use pageup and
pagedown much when I'm writing (and thus have both hands on the
keyboard) because Emacs but when browsing it's handy. I feel like I
would get confused about whether up is on the left or the right. But
this is probably just a personal quirk; I suspect most people who have
laptops with trackpads don't use pageup/pagedown as much as I do. I'd be
interested in hearing more peoples' perspectives.

**Comment by dbordak** [comment]
I don't really see having pairs on the same finger as being a problem, but how about splitting them across the "spine," then?

**Comment by technomancy** [comment]
Typing `()` or `{}` is a lot faster when the open and close bracket use different fingers, though of course it doesn't really affect `( ... )` much.

Splitting the brackets up so that one hand is responsible for either side sounds interesting. I will have to try it out.

**Comment by dbordak** [comment]
Yeah, what I meant was that I don't often have to type `()` or such, it's almost always `(...)`

**Comment by Fuco1** [comment]
Re. pg up/down, I would personally prefer to put it one above the other.  There is hardly anything that infuriates me more on most modern (laptop) keyboards as the placement of home/end and pgup/down in rows... you never know which to hit to get where you want (bonus points if both are on the same key and you have to FN to switch).

Also, why would you ever need `)`? :D

**Comment by lorentrogers** [comment]
A big +1 from me on this one. I have to switch between linux and windoze for work, and unfortunately nothing supports j and k for up/down. I had assumed that the layer 2 key was a momentary function, but since it's a modal toggle, I end up accidentally triggering the reset function all the time. If we can't resolve a new layout in this thread, could we at least have layer 2 be momentary?

**Comment by technomancy** [comment]
I've implemented the layout above as `layout_qwerty_alt.h` in this codebase; however, I am considering changing it to the default layout as part of a move to also switch to recommending the TMK firmware as the default. However, there are still some issues there (like https://github.com/technomancy/tmk_keyboard/issues/13) that need to be resolved first. But if you'd like to test it out, it is a lot more featureful and flexible, even though the code can be more difficult to read at times. I would be interested in getting feedback on it.

**Comment by lorentrogers** [comment]
Having tried out the TMK firmware, I can say that a lot of my original troubles will be solved. The updated layout with the arrow keys on L1 makes a lot of sense. Also, the fact that the reset key is mapped to B instead eliminates the whole accidental-reset issue.

**Comment by jevonearth** [comment]
Thanks @technomancy 

I finally flashed the latest TMK firmware. Will see how it goes. Are there updated .svg images for these new layers?

**Comment by jevonearth** [comment]
Feedback; After a day of using the new layout (using the TMK firmware) my keyboard experience is much better. Thank you.

**Comment by technomancy** [comment]
Excellent; thanks for the feedback!

**Comment by lorentrogers** [comment]
Agreed. Much better than the original design. 

Also, I don't think there are layout maps yet. I started putting one together, but I've not yet had a chance to finish it. (Writing them in on a blank printout was quicker...) If there's interest, I can put up a pull request with my progress. Since I work on Linux, I found a few issues with the original files, so I made a fair amount of mods. They ended up looking somewhat ugly, but functional.

**Comment by technomancy** [comment]
Since the feedback has been nearly all positive, I will move forward on
making this the default, including getting an updated cheat sheet SVG.

> Since I work on Linux, I found a few issues with the original files,
> so I made a fair amount of mods. They ended up looking somewhat ugly,
> but functional.

Could you explain what these are? It might be nice to include an
alternate layout for others who run into similar issues.

**Comment by jevonearth** [comment]
For the hell of me, I can't find the percentage symbol on this new layout!
Any hints?

**Comment by lorentrogers** [comment]
Shift+5 = %
Shift+4 = $

**Comment by technomancy** [comment]
Unfortunately the downside of having the arrows on the fn layer is that
four keys had to be removed to make room; they are %, ^, |, and ~. Of
course you can still hit them, but you have to use fn and shift together.

**Comment by jevonearth** [comment]
No problem, now I know.

For the cheat sheet SVG's, I think it would be immensely helpful to
newcomers if each key also shows the shift variant, perhaps in the top
right of each key. Might be awkward to generate though.

Personally I don't need it now, as I have learned where those keys are. :)

**Comment by technomancy** [comment]
Closing this as other firmwares (QMK; Kaleidoscope) are clear improvements over this one.
