### ISSUE TITLE
Can't software-reset anymore

### ISSUE THREAD

**Issue by drewr** [technomancy/atreus-firmware#29]
I'm using firmware from b8ceaa4 master branch, and I can no longer use L2-enter to reset the board. Watching the logs, nothing happens. Keys still work; it just seems to ignore the reset. (Unplugging does produce activity in the log, though, so I seem to be looking in the right place.)

**Comment by drewr** [comment]
That behavior is on my Ubuntu 15.04 Vivid desktop. I just tried on my `MacBookAir6,1` and it resets correctly. Another silly Ubuntu issue? How would the OS determine whether the kbd itself could be RST?

**Comment by technomancy** [comment]
There was a bug in the USB stack for that release of Ubuntu; it got fixed in the next one.
