### ISSUE TITLE
Doesn't work with Handheld Scientific bluetooth keyboard adapter

### ISSUE THREAD

**Issue by cy384** [technomancy/atreus-firmware#33]
My Atreus with this firmware does not function properly with the [Handheld Scientific bluetooth keyboard adapter](http://handheldsci.com/kb), unlike every other pure USB keyboard (i.e. without an integrated hub or other features) I tested.  Keypresses are delayed significantly or dropped entirely.

I feel slightly bad making this bug report, since I have no intention of investigating further, but the information may be useful to someone else.

Workaround: use Atreus TMK firmware instead.

**Comment by ajcampbell1333** [comment]
Did you purchase that adapter from handheldsci.com? I tried to purchase one a month ago. I was billed $50, but the adapter was never sent.  I can't reach anyone there. They don't respond to emails, and the phone # belongs to some random lady in Oklahoma who has never heard of Handheld Scientific. If you bought one, it must have been a real company at one point, but now it looks like they're just thieves.

**Comment by F1LT3R** [comment]
I had the same issue with a different Bluetooth adapter. I think the Atreus is not standards compliant, and so it can do some weird things on some devices.

**Comment by technomancy** [comment]
Yeah, I would strongly recommend using QMK or Kaleidoscope for this instead; as per the notice in the readme this repo is kept around mostly for instructional purposes and isn't recommended for normal use.
