### ISSUE TITLE
multidvorak: incorrect "reset" documentation

### ISSUE THREAD

**Issue by bmatsuo** [technomancy/atreus-firmware#38]
The documentation regarding resetting the firmware after loading the multidvorak layout is incorrect.

From [multidvorak.h](https://github.com/technomancy/atreus-firmware/blob/master/multidvorak.h#L13-L15)
> Hitting Enter on this layer will reset the microcontroller in order to allow new firmware to be uploaded.

For some reason the commit d04151e1 changed the location of the reset key to a [position](https://github.com/technomancy/atreus-firmware/blob/master/multidvorak.h#L33) between KEY_PAGE_DOWN and KEY_BACKSPACE.

I don't really understand why the key position was changed (if it was indeed intentional). But either the layout or the documentation should be changed.

**Comment by technomancy** [comment]
Good catch; fixed in 6dd7daf.

This was changed because it's easy to hit the bottom right key of L2 accidentally when switching out of L2.

**Comment by bmatsuo** [comment]
Thanks for the update @technomancy.

Good to know the change was intentional. But I'm a still confused why it is inconsistent with the other layouts provided here? Isn't the problem you describe a general danger for anyone switching into L2 regardless of their chosen layout?

IMHO it seems like RESET shouldn't be triggered by a **single** key on L2, no matter where it is placed. But that sounds like an entirely different issue to me.

**Comment by technomancy** [comment]
> Good to know the change was intentional. But I'm a still confused why
> it is inconsistent with the other layouts provided here?

I have been planning on switching all the other ones over to it, but I
haven't gotten around to getting more feedback from others on the
mailing list yet, and I wanted to run it through the paces in my own
layout first. Thanks for the reminder. =)

> Isn't the problem you describe a general danger for anyone switching
> into L2 regardless of their chosen layout?

Theoretically, but the problem really only arises when you want to type
a string of keycodes where all but the last one is on L2. In practice
this only happens when the last key is enter; having a sequence of
function keys followed by a "b" is very rare.

**Comment by bmatsuo** [comment]
I'm not sure I agree with you. While editing a text document arrow key presses on L2 can be followed by a "b", just as they might be followed by a newline. But I'm just being difficult at this point.  I'm sure that L2 followed by Enter is more common than L2 followed by "b". And I haven't really experienced such pain.

I type using vi bindings most of the time so I don't use the arrow keys in that way. I pretty much avoid F* keys altogether. So I don't even enter L2 often. And I don't have much of an opinion one way or the other. I really just needed the clarification about consistency which you provided. Thanks again.

**Comment by technomancy** [comment]
Yeah I don't really use L2 much either; I'm just going from suggestions from people on the mailing list.
