### ISSUE TITLE
multidvorak: cannot get out of "hardware dvorak" mode using a key combination

### ISSUE THREAD

**Issue by bmatsuo** [technomancy/atreus-firmware#40]
After trying out several things and looking over the layout code for the multidvorak layout it appears to me that there is no way to get back to the "software dvorak" layout orbit one hardware dvorak mode has been entered. Entering hardware dvorak mode sets the `base_layer` variable to 3. And I do not see a way for that variable to be reset to 0. One needs to unplug the device or reset the firmware. This is not necessarily a problem. But I think it should be documented at the very least.

However, it seems to me that the same key combination that puts one into hardware dvorak mode should allow them to escape back to software dvorak mode. I've put together a branch which does this. In my limited testing it seems to be working. If you would like I will open a pull request with these changes.

https://github.com/technomancy/atreus-firmware/compare/master...bmatsuo:bmatsuo/multidvorak-return-to-sw-translation

**Comment by technomancy** [comment]
Haha; good point. I never even considered this because the use case for hardware dvorak is "I'm using my keyboard on someone else's computer" in which case I want it to stay that way until I unplug it. But we might as well include a way to leave it for completeness sake.

**Comment by bmatsuo** [comment]
At first I actually forgot that unplugging the device would reset the device state :stuck_out_tongue_winking_eye:  I'm pretty new to embedded work. I will open a pull request.
