### ISSUE TITLE
trying to re-flash firmware on OSX, keyboard doesn't show up in /dev/

### ISSUE THREAD

**Issue by benswift** [technomancy/atreus-firmware#42]
After building the keyboard I installed the basic atreus firmware no worries, it showed up as `/dev/cu.usbmodemXXXX`. Now I'd like to re-flash the firmware to change the layout. However, when I plug the keyboard in it doesn't show up in `/dev/` anymore (the `diff` of `ls /dev` between keyboard plugged/unplugged is empty).  The system responds to the key presses, but the only place I can see it listed is under `Atreus` under the USB tab in System Profiler.

Any ideas?  My backup plan is to just try and re-flash it on Linux, but it would be nice to figure out why it's not showing up anymore on OSX 10.11.

**Comment by technomancy** [comment]
Once the firmware has been flashed, it won't show up in /dev unless it's
in bootloader mode. You can activate bootloader mode by hitting the key
marked "reset" in the default layout, or if that doesn't work, by
opening up and connecting the reset and ground pins like you did when
you first built it.

It is expected for the keyboard to not show up in /dev during normal
operation. Hope that clears things up.

**Comment by benswift** [comment]
Cool, thanks mate - worked a treat.  My bad for not rtfm carefully. You
can close this one.

**Comment by technomancy** [comment]
No problem.

**Comment by neeasade** [comment]
Hello, I am experiencing the same during keyboard assembly (on linux though). 

I have just installed the controller and plugged it in and compared /dev/ contents after sending the controller into bootload mode (indicated by the LED change to fast flashing, right?) and am not seeing it -- I'm also not seeing anything in the output of dmesg however. Does this indicate possible error in soldering?

**Comment by technomancy** [comment]
> I have just installed the controller and plugged it in and compared
> /dev/ contents after sending the controller into bootload mode
> (indicated by the LED change to fast flashing, right?) and am not
> seeing it -- I'm also not seeing anything in the output of dmesg
> however. Does this indicate possible error in soldering?

It's very unlikely that this is an error in soldering. Do you see
anything in dmesg when inserting or removing the cable regardless of the
reset procedure?

The LED status you should be expecting isn't so much a fast flashing as a
slow gradual pulsing, so it sounds like maybe it's not actually entering
bootloader mode. If bootloader mode is achieved, it will pulse for 8
seconds before returning to normal mode, which consists of on/off flashing.

**Comment by neeasade** [comment]
> It's very unlikely that this is an error in soldering. 

Hi there, actually it was -- I just went over all my points on the controller again with the iron and then it worked. ¯\_(ツ)_/¯

> Do you see anything in dmesg when inserting or removing the cable regardless of the
reset procedure?

I was not. 


> If bootloader mode is achieved, it will pulse for 8
seconds before returning to normal mode, which consists of on/off flashing.

This is what I was experiencing (pulse I described as fast flashing)

**Comment by technomancy** [comment]
Great; glad you got it working.
