### ISSUE TITLE
Discussion forum?

### ISSUE THREAD

**Issue by lorenrogers** [technomancy/atreus-firmware#47]
Is there a designated place for discussing things related to the Atreus? I feel like there should be a Gitter chat, or a designated forum. I'm sure folks will come up with all kinds of layouts / improvements / etc. 

If this already exists, it should probably be added to the readme.

**Comment by gerbercj** [comment]
Good point... we should probably at least add the mailing list to the readme:
https://www.freelists.org/list/atreus

**Comment by technomancy** [comment]
The mailing list actually already mentioned in the readme. I have created the
#atreus-kb channel on Freenode (#atreus was taken), but I suspect with
the level of discussion we've seen that the mailing list and GitHub
issues will end up being used more.
