### ISSUE TITLE
Swap the arrow and F keys

### ISSUE THREAD

**Issue by lorenrogers** [technomancy/atreus-firmware#48]
Personally, I'm very used to having the arrow keys on my right hand. I know that the wasd directional keys are often used elsewhere, but for folks like me, it may be nice to have the option of flipping them with the F keys. I do like how the F keys match the number pad in the default layout, but the usability of the arrow keys is more important to me.

What I'm thinking is that the home, end, page up, and page down keys all move where the F keys are, and vice-versa. Since the arrow keys would now be on the right hand, there would be no need to duplicate the up and down buttons on the right -- freeing up two extra keys for alternative mappings.

I'd like to see where issue #46 lands before I work on prototyping this.

**Comment by technomancy** [comment]
Closing this as other firmwares (QMK; Kaleidoscope) are clear improvements over this one.
