### ISSUE TITLE
Key Repeating

### ISSUE THREAD

**Issue by F1LT3R** [technomancy/atreus-firmware#53]
I have two Atreus keyboards. Both of them repeat the top-right key. ("L" for me in Dvorak)

It happens most after hitting "L" shortly after another key, especially the Enter key (bottom right).

Usually it repeats twice "LL", sometimes three times "LLL".

Try it yourself, what do you see?

Again, this happens on both keyboards, and only with this key. I have tried different cables. I have tried different computers. Same behavior.

I have not changed the firmware since the original flash on both keyboards. I have not noticed this behavior until now.

Has anyone else seem anything like this?

**Comment by technomancy** [comment]
The most common cause for this problem when it affects a single key is a
cold solder joint. An easy way to check is to just re-flow the solder
for this key.

If it really is a problem with the firmware, you should try QMK instead
as it is much more featureful.

**Comment by F1LT3R** [comment]
Thanks @technomancy ! I will try this tonight.
Strange that I would manage to badly solder the same key on both keyboards... unless maybe *all* my keys are badly soldered :) (probably true)
